# Banco de Dados MySQL (para producao)
spring.datasource.url=jdbc:mysql://localhost:3306/cafearomaesabor
spring.datasource.username=root
spring.datasource.password=senha
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
